# fly.toml app configuration file generated for jess-sebi on 2025-01-05T22:58:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jess-sebi'
primary_region = 'ams'
console_command = '/rails/bin/rails console'

[env]
  CANONICAL_HOST = 'jess-sebi.fly.dev'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
